// switch case

let result:string='C'
switch(result){
     case'A':
     console.log('you are a good student!')
    break;
    case'B':
    console.log('you are a nice student')
    break;
    case'C':
    console.log('you are a lukky student')
    break;
    default:
        console.log('invalid code')
}

// //--------------------------------------------------------

// let marksheet: number = 71;
// switch (true) {
//   case marksheet >= 80 && marksheet <= 100:
//     console.log("Grade A+one");
//     break;
//   case marksheet >= 70 && marksheet <= 80:
//     console.log("Grade A");
//     break;
//   case marksheet >= 60 && marksheet <= 70:
//     console.log("Grade B");
//     break;
//   case marksheet >= 50 && marksheet <= 60:
//     console.log("Grade C");
//     break;
//   case marksheet >= 40 && marksheet <= 50:
//     console.log("Grade D");
//     break;
//   default:
//     console.log("invalid code");
// }

//--------------------------------------

// let salary: number = 71000;

// switch (true) {
//   case salary >= 90000 && salary <= 100000:
//     console.log("Manager salary 95000");
//     break;
//   case salary >= 80000 || salary <= 90000:
//     console.log("Management salary 85000");
//     break;
//   case salary >= 70000 !: salary <= 80000;
//     console.log("Staff salary 75000");
//     break;
//   default:
//     console.log("invalid");
// }
